Repository TCodeNg/Tcode-mono, pull requests merged in 2020-07, with the labels that each got.

#95 chore(product): milestone commit
  apps/storefront-api/src/app/product/product.controller.ts
  apps/storefront-api/src/app/product/product.service.ts
  libs/api-interface/src/lib/product/product-dto.ts
Labels: enhancement

#94 Reuseable input component
  .github/stale.yml
  CODE_OF_CONDUCT.md
  apps/storefront-api/src/app/product/product.controller.spec.ts
  apps/storefront-api/src/app/product/product.controller.ts
  apps/storefront-api/src/app/product/product.module.ts
  apps/storefront-api/src/app/product/product.service.ts
  apps/storefront-api/src/main.ts
  apps/storefront/src/app/app.component.ts
  libs/api-interface/src/lib/product/product.doc.ts
  libs/api-interface/src/lib/product/product.ts
  libs/api-interface/src/lib/product/schema.ts
  libs/input/README.md
  libs/input/jest.config.js
  libs/input/src/index.ts
  libs/input/src/lib/input.module.spec.ts
  libs/input/src/lib/input.module.ts
  libs/input/src/lib/input/input.component.html
  libs/input/src/lib/input/input.component.scss
  libs/input/src/lib/input/input.component.spec.ts
  libs/input/src/lib/input/input.component.ts
  libs/input/src/lib/inputError.directive.ts
  libs/input/src/test-setup.ts
  libs/input/tsconfig.json
  libs/input/tsconfig.lib.json
  libs/input/tsconfig.spec.json
  libs/input/tslint.json
  libs/sentry/README.md
  libs/sentry/jest.config.js
  libs/sentry/src/index.ts
  libs/sentry/src/lib/sentry.interceptor.spec.ts
  libs/sentry/src/lib/sentry.interceptor.ts
  libs/sentry/src/lib/sentry.module.ts
  libs/sentry/tsconfig.json
  libs/sentry/tsconfig.lib.json
  libs/sentry/tsconfig.spec.json
  libs/sentry/tslint.json
  nx.json
  package-lock.json
  package.json
  tsconfig.json
  workspace.json
Labels: enhancement

#101 F/media uploader
  .gitignore
  apps/storefront-api/src/app/app.module.ts
  apps/storefront/src/app/app.component.ts
  apps/storefront/src/styles.scss
  libs/api-interface/src/lib/image.ts
  libs/card/README.md
  libs/card/jest.config.js
  libs/card/src/index.ts
  libs/card/src/lib/_card.scss
  libs/card/src/lib/card.module.spec.ts
  libs/card/src/lib/card.module.ts
  libs/card/src/lib/card/card.component.html
  libs/card/src/lib/card/card.component.scss
  libs/card/src/lib/card/card.component.spec.ts
  libs/card/src/lib/card/card.component.ts
  libs/card/src/lib/model.ts
  libs/card/src/test-setup.ts
  libs/card/tsconfig.json
  libs/card/tsconfig.lib.json
  libs/card/tsconfig.spec.json
  libs/card/tslint.json
  libs/input/README.md
  libs/input/jest.config.js
  libs/input/src/index.ts
  libs/input/src/lib/input.module.spec.ts
  libs/input/src/lib/input.module.ts
  libs/input/src/lib/input/input.component.html
  libs/input/src/lib/input/input.component.scss
  libs/input/src/lib/input/input.component.spec.ts
  libs/input/src/lib/input/input.component.ts
  libs/input/src/lib/inputError.directive.ts
  libs/input/src/test-setup.ts
  libs/input/tsconfig.json
  libs/input/tsconfig.lib.json
  libs/input/tsconfig.spec.json
  libs/input/tslint.json
  libs/media-api/README.md
  libs/media-api/jest.config.js
  libs/media-api/src/index.ts
  libs/media-api/src/lib/image.service.spec.ts
  libs/media-api/src/lib/image.service.ts
  libs/media-api/src/lib/media-api.module.ts
  libs/media-api/src/lib/media-transport/cloudinary-transport.ts
  libs/media-api/src/lib/media-transport/index.ts
  libs/media-api/src/lib/media-transport/media-transport.ts
  libs/media-api/src/lib/media-transport/transport.service.spec.ts
  libs/media-api/src/lib/media-transport/transport.service.ts
  libs/media-api/src/lib/media.controller.spec.ts
  libs/media-api/src/lib/media.controller.ts
  libs/media-api/tsconfig.json
  libs/media-api/tsconfig.lib.json
  libs/media-api/tsconfig.spec.json
  libs/media-api/tslint.json
  nx.json
  package-lock.json
  package.json
  tsconfig.json
  workspace.json
Labels: enhancement

#117 F/frontend auth
  apps/storefront/src/app/app.component.html
  apps/storefront/src/app/app.module.ts
  apps/storefront/src/app/landing/landing.component.css
  apps/storefront/src/app/landing/landing.component.html
  apps/storefront/src/app/landing/landing.component.spec.ts
  apps/storefront/src/app/landing/landing.component.ts
  apps/storefront/src/app/landing/landing.module.ts
  libs/frontend-auth/README.md
  libs/frontend-auth/jest.config.js
  libs/frontend-auth/src/index.ts
  libs/frontend-auth/src/lib/+state/actions.ts
  libs/frontend-auth/src/lib/+state/auth.state.model.ts
  libs/frontend-auth/src/lib/+state/auth.state.ts
  libs/frontend-auth/src/lib/+state/index.ts
  libs/frontend-auth/src/lib/_auth.structure.scss
  libs/frontend-auth/src/lib/_media.scss
  libs/frontend-auth/src/lib/auth.config.ts
  libs/frontend-auth/src/lib/auth.guard.spec.ts
  libs/frontend-auth/src/lib/auth.guard.ts
  libs/frontend-auth/src/lib/auth.interceptor.spec.ts
  libs/frontend-auth/src/lib/auth.interceptor.ts
  libs/frontend-auth/src/lib/auth.service.spec.ts
  libs/frontend-auth/src/lib/auth.service.ts
  libs/frontend-auth/src/lib/frontend-auth.module.spec.ts
  libs/frontend-auth/src/lib/frontend-auth.module.ts
  libs/frontend-auth/src/lib/login/login.component.html
  libs/frontend-auth/src/lib/login/login.component.scss
  libs/frontend-auth/src/lib/login/login.component.spec.ts
  libs/frontend-auth/src/lib/login/login.component.ts
  libs/frontend-auth/src/test-setup.ts
  libs/frontend-auth/tsconfig.json
  libs/frontend-auth/tsconfig.lib.json
  libs/frontend-auth/tsconfig.spec.json
  libs/frontend-auth/tslint.json
  libs/shared/assets/src/lib/img/facebook.svg
  libs/shared/assets/src/lib/img/heart.svg
  libs/shared/assets/src/lib/img/instagram.svg
  libs/shared/assets/src/lib/img/logo.png
  libs/shared/assets/src/lib/img/menu.svg
  libs/shared/assets/src/lib/img/search.svg
  libs/shared/assets/src/lib/img/twitter.svg
  libs/shared/assets/src/lib/img/user.svg
  nx.json
  package-lock.json
  package.json
  tsconfig.json
  workspace.json
Labels: enhancement

#121 feat(register): bootstrap registration component
  libs/frontend-auth/src/lib/_auth.structure.scss
  libs/frontend-auth/src/lib/frontend-auth.module.ts
  libs/frontend-auth/src/lib/login/login.component.html
  libs/frontend-auth/src/lib/login/login.component.scss
  libs/frontend-auth/src/lib/register/register.component.html
  libs/frontend-auth/src/lib/register/register.component.scss
  libs/frontend-auth/src/lib/register/register.component.spec.ts
  libs/frontend-auth/src/lib/register/register.component.ts
  libs/shared/assets/src/lib/img/back-arrow-blue.png
Labels: enhancement

#123 fix(register): fix typo
  apps/storefront/src/app/app.module.ts
  libs/frontend-auth/src/lib/register/register.component.html
Labels: bug

#124 feat(auth): bootstrap reset password component
  libs/frontend-auth/src/lib/frontend-auth.module.ts
  libs/frontend-auth/src/lib/reset-password/reset-password.component.html
  libs/frontend-auth/src/lib/reset-password/reset-password.component.scss
  libs/frontend-auth/src/lib/reset-password/reset-password.component.spec.ts
  libs/frontend-auth/src/lib/reset-password/reset-password.component.ts
Labels: enhancement, feature_request

#118 Stage/storefront
  apps/storefront/src/app/app.component.html
  apps/storefront/src/app/app.module.ts
  apps/storefront/src/app/landing/landing.component.css
  apps/storefront/src/app/landing/landing.component.html
  apps/storefront/src/app/landing/landing.component.spec.ts
  apps/storefront/src/app/landing/landing.component.ts
  apps/storefront/src/app/landing/landing.module.ts
  libs/frontend-auth/README.md
  libs/frontend-auth/jest.config.js
  libs/frontend-auth/src/index.ts
  libs/frontend-auth/src/lib/+state/actions.ts
  libs/frontend-auth/src/lib/+state/auth.state.model.ts
  libs/frontend-auth/src/lib/+state/auth.state.ts
  libs/frontend-auth/src/lib/+state/index.ts
  libs/frontend-auth/src/lib/_auth.structure.scss
  libs/frontend-auth/src/lib/_media.scss
  libs/frontend-auth/src/lib/auth.config.ts
  libs/frontend-auth/src/lib/auth.guard.spec.ts
  libs/frontend-auth/src/lib/auth.guard.ts
  libs/frontend-auth/src/lib/auth.interceptor.spec.ts
  libs/frontend-auth/src/lib/auth.interceptor.ts
  libs/frontend-auth/src/lib/auth.service.spec.ts
  libs/frontend-auth/src/lib/auth.service.ts
  libs/frontend-auth/src/lib/frontend-auth.module.spec.ts
  libs/frontend-auth/src/lib/frontend-auth.module.ts
  libs/frontend-auth/src/lib/login/login.component.html
  libs/frontend-auth/src/lib/login/login.component.scss
  libs/frontend-auth/src/lib/login/login.component.spec.ts
  libs/frontend-auth/src/lib/login/login.component.ts
  libs/frontend-auth/src/lib/register/register.component.html
  libs/frontend-auth/src/lib/register/register.component.scss
  libs/frontend-auth/src/lib/register/register.component.spec.ts
  libs/frontend-auth/src/lib/register/register.component.ts
  libs/frontend-auth/src/lib/reset-password/reset-password.component.html
  libs/frontend-auth/src/lib/reset-password/reset-password.component.scss
  libs/frontend-auth/src/lib/reset-password/reset-password.component.spec.ts
  libs/frontend-auth/src/lib/reset-password/reset-password.component.ts
  libs/frontend-auth/src/test-setup.ts
  libs/frontend-auth/tsconfig.json
  libs/frontend-auth/tsconfig.lib.json
  libs/frontend-auth/tsconfig.spec.json
  libs/frontend-auth/tslint.json
  libs/shared/assets/src/lib/img/back-arrow-blue.png
  libs/shared/assets/src/lib/img/facebook.svg
  libs/shared/assets/src/lib/img/heart.svg
  libs/shared/assets/src/lib/img/instagram.svg
  libs/shared/assets/src/lib/img/logo.png
  libs/shared/assets/src/lib/img/menu.svg
  libs/shared/assets/src/lib/img/search.svg
  libs/shared/assets/src/lib/img/twitter.svg
  libs/shared/assets/src/lib/img/user.svg
  nx.json
  package-lock.json
  package.json
  tsconfig.json
  workspace.json
Labels: enhancement
