Repository TCodeNg/Tcode-mono, pull requests merged in 2020-06, with the labels that each got.

#44 F/product rating
  apps/storefront/src/app/app.component.html
  apps/storefront/src/app/app.module.ts
  libs/productrating/README.md
  libs/productrating/jest.config.js
  libs/productrating/src/index.ts
  libs/productrating/src/lib/product-rating/product-rating.component.html
  libs/productrating/src/lib/product-rating/product-rating.component.scss
  libs/productrating/src/lib/product-rating/product-rating.component.spec.ts
  libs/productrating/src/lib/product-rating/product-rating.component.ts
  libs/productrating/src/lib/productrating.module.spec.ts
  libs/productrating/src/lib/productrating.module.ts
  libs/productrating/src/test-setup.ts
  libs/productrating/tsconfig.json
  libs/productrating/tsconfig.lib.json
  libs/productrating/tsconfig.spec.json
  libs/productrating/tslint.json
  libs/shared/assets/img/Star.svg
  libs/shared/assets/img/Star_light.svg
  nx.json
  tsconfig.json
  workspace.json
Labels: enhancement

#63 F/product
  apps/storefront-api/src/app/product/product.controller.ts
  apps/storefront-api/src/app/product/product.module.ts
  apps/storefront-api/src/app/product/product.service.ts
  apps/storefront-api/src/main.ts
  libs/api-interface/src/lib/product/index.ts
  libs/api-interface/src/lib/product/product.ts
  libs/api-interface/src/lib/product/rate-product.dto.ts
  libs/api-interface/src/lib/rating.ts
  libs/imagepreview/src/lib/imagepreview/imagepreview.component.ts
  libs/imagepreview/src/lib/img-banner/img-banner.component.ts
  libs/imagepreview/src/lib/img-thumbnail/img-thumbnail.component.ts
  libs/product/README.md
  libs/product/jest.config.js
  libs/product/src/index.ts
  libs/product/src/lib/product-image/product-image.component.html
  libs/product/src/lib/product-image/product-image.component.scss
  libs/product/src/lib/product-image/product-image.component.spec.ts
  libs/product/src/lib/product-image/product-image.component.ts
  libs/product/src/lib/product-item/product-item.component.html
  libs/product/src/lib/product-item/product-item.component.scss
  libs/product/src/lib/product-item/product-item.component.spec.ts
  libs/product/src/lib/product-item/product-item.component.ts
  libs/product/src/lib/product.module.spec.ts
  libs/product/src/lib/product.module.ts
  libs/product/src/test-setup.ts
  libs/product/tsconfig.json
  libs/product/tsconfig.lib.json
  libs/product/tsconfig.spec.json
  libs/product/tslint.json
  libs/shared/assets/img/shopping-bag.svg
  nx.json
  package-lock.json
  package.json
  tsconfig.json
  workspace.json
Labels: enhancement

#67 fix(product rating): fix total score
  apps/storefront-api/src/app/product/product.service.spec.ts
  libs/api-interface/src/lib/product/product-rating.ts
Labels: bug

#77 F/product
  .github/stale.yml
  CODE_OF_CONDUCT.md
  apps/storefront-api/src/app/product/product.controller.spec.ts
  apps/storefront-api/src/app/product/product.controller.ts
  apps/storefront-api/src/app/product/product.module.ts
  apps/storefront-api/src/app/product/product.service.ts
  apps/storefront-api/src/main.ts
  libs/sentry/README.md
  libs/sentry/jest.config.js
  libs/sentry/src/index.ts
  libs/sentry/src/lib/sentry.interceptor.spec.ts
  libs/sentry/src/lib/sentry.interceptor.ts
  libs/sentry/src/lib/sentry.module.ts
  libs/sentry/tsconfig.json
  libs/sentry/tsconfig.lib.json
  libs/sentry/tsconfig.spec.json
  libs/sentry/tslint.json
  nx.json
  package-lock.json
  package.json
  tsconfig.json
  workspace.json
Labels: enhancement

#84 Stage/api
  apps/storefront-api/src/app/product/product.controller.ts
  apps/storefront-api/src/app/product/product.service.ts
  libs/api-interface/src/lib/product/product.doc.ts
  libs/api-interface/src/lib/product/schema.ts
Labels: enhancement

#87 chore(product): milestone
  apps/storefront-api/src/app/product/product.module.ts
  apps/storefront-api/src/app/product/product.service.ts
  apps/storefront-api/src/main.ts
  libs/api-interface/src/lib/product/product.doc.ts
  libs/api-interface/src/lib/product/product.ts
  libs/api-interface/src/lib/product/schema.ts
  package-lock.json
  package.json
Labels: enhancement, feature_request

#89 fix(product): prevent rating of deleted products
  apps/storefront-api/src/app/product/product.service.ts
Labels: bug

#88 Stage/api
  apps/storefront-api/src/app/product/product.module.ts
  apps/storefront-api/src/app/product/product.service.ts
  apps/storefront-api/src/main.ts
  libs/api-interface/src/lib/product/product.doc.ts
  libs/api-interface/src/lib/product/product.ts
  libs/api-interface/src/lib/product/schema.ts
  package-lock.json
  package.json
Labels: bug, enhancement
